### ISSUE TITLE
CSS Build Process

### ISSUE THREAD

**Issue by buzzedword** [bizzabo/new-relic-boxes#17]
Just wanted to create an item in here to gauge interest level.

Because of #7, the `gulpfile.js` is going to become a bit more defined soon to account for the JS processing. The CSS in this project is pretty clear already, and I was wondering if you wanted any kind of tooling to wrap it.

We have options such as:
### Preprocessors
- LESS
- SASS
- Stylus
### Postprocessors
- PostCSS
  - Autoprefixr
  - Nesting
  - CSS4

Or, honestly, just a "get off my lawn, concat it all, go away" approach. Anything here is fine, I just wanted to get an idea of what you had in mind moving forward-- I can tool any number of them up for you.

**Comment by danielbentov** [comment]
I prefer LESS.
From my point of view it is import to keep this project light and simple to use.
We aim it to be a plug and play dashboard with as less dependencies as we can.
