### ISSUE TITLE
Chrome: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by mathewpeterson** [bizzabo/new-relic-boxes#2]
I am on OSX 10.10 using Chrome 43.0.2357.81 (64-bit) and I am unable to load any data from New Relic

![screen shot 2015-06-16 at 11 48 52 am](https://cloud.githubusercontent.com/assets/203190/8188818/beb5d7a0-141d-11e5-90be-bd969defa794.png)

**Comment by tkrajcar** [comment]
Guessing you are running Ghostery, which sledgehammers `*.newrelic.com` by default. Whitelist New Relic in the Ghostery UI and you should be good.

**Comment by mathewpeterson** [comment]
I'm not sure what Ghostery UI but I did have an adblock extension installed. I've whitelisted the New Relic site and it seems to work well!

Thank you!
