### ISSUE TITLE
Document parseData a bit for more transparency

### ISSUE THREAD

**Issue by buzzedword** [bizzabo/new-relic-boxes#9]
Could you wrap a few inline comments around https://github.com/bizzabo/new-relic-boxes/blob/bce636cd6019405d43167558cb128a454ee58917/app/js/main.js#L31-L73 to clarify what this method is doing step by step? I could probably break it down a bit more into services if it was a bit less opaque, and make it more testable.

**Comment by danielbentov** [comment]
Sure, will do.
